#!/usr/bin/env sh
set -eu -o pipefail

golang_version=${1-}

dockerfile=dobifiles/Dockerfile
if [ -n "$golang_version" ]; then
    sed -i -e 's/FROM\s\+golang.*/FROM golang:'"${golang_version}"'/' $dockerfile
fi

echo "COPY . ." >> $dockerfile
image="cli-builder:$CIRCLE_BUILD_NUM"
docker build -f "$dockerfile" --tag "$image" .
docker run --name \
    "test-$CIRCLE_BUILD_NUM" "$image" \
    bash -ec 'dep ensure; scripts/binary-testsum; scripts/test-unit'
